### ISSUE TITLE
change the font

### ISSUE THREAD

**Issue by atmonshi** [pishran/nova-rtl-theme#1]
hi  👋  ,
is there a way to change the font and use custom font instead of `Vazir` ?

and thank you for this RTL theme .

**Comment by FaridAghili** [comment]
Hi Ashraf,
I didn't thought about that and currently there isn't a way for it.

For now the solution could be like:
1. Skip the assets publish as you don't need the Vazir font.
2. Remove line 1 to 59 of [theme.scss](https://github.com/pishran/nova-rtl-theme/blob/master/resources/scss/theme.scss).
3. Import your preferred font in `theme.scss` (using `@import` ?).
4. Change `font-family` in line 62 of [theme.scss](https://github.com/pishran/nova-rtl-theme/blob/master/resources/scss/theme.scss).
5. Compile modified `theme.scss` and replace [theme.css](https://github.com/pishran/nova-rtl-theme/blob/master/resources/css/theme.css).

**Comment by atmonshi** [comment]
i made [some changes](https://github.com/wa7eedem/nova-rtl-theme/tree/add-font) , if you like for me to open a PR , let me know ..

I add the `npm` script that needed to recompile the css file , also make it simple to change the fonts by separating the font definitions in `_font.scss` file , so the edit will be in one file .

also your solution is very great for developments , but in production its not possible , currently i am using my fork for this .

must be a better way to customize the fonts 🤔

**Comment by FaridAghili** [comment]
+1 for separating the font definitions.

I think there should be a way to define the font in a config file so no need to modify & recompile at all.

I'm going to let this issue be open and gonna find a way to achieve that in a couple of days.

**Comment by FaridAghili** [comment]
I've released v1.2.0 which enables you to select your desired font in config file.

All you need is to define your CSS file url (local or remote) and font family.

Check the readme, give it a try, and let me know how it goes.

**Comment by atmonshi** [comment]
very nice idea  😄 ,

<img width="1227" alt="Screen Shot 2019-06-02 at 12 02 17 AM" src="https://user-images.githubusercontent.com/1952412/58753609-72745e80-84ca-11e9-815b-5e416f26749e.png">

It’s s work as a charm , thank you .

**Comment by FaridAghili** [comment]
Good to know that, your welcome.
