### ISSUE TITLE
in_array() expects parameter 2 to be array, null given

### ISSUE THREAD

**Issue by SadeghPM** [pishran/nova-rtl-theme#11]
Hi
Somehow `config('nova-rtl-theme.locales')` in Pishran\NovaRtlTheme\ThemeServiceProvider::boot at line 18 return `null` and cause exception : `in_array() expects parameter 2 to be array, null given` exception.

![Screenshot from 2021-01-23 11-50-58](https://user-images.githubusercontent.com/9298600/105573243-4ed1ec00-5d71-11eb-827f-f921f53c91d0.png)

This could be solve by adding an empty array for default value in  `config('nova-rtl-theme.locales')` .

**Comment by FaridAghili** [comment]
Merged & Released
Thank you
