### ISSUE TITLE
Alignment for dropdown is still unresolved

### ISSUE THREAD

**Issue by ImanR7** [pishran/nova-rtl-theme#13]
@FaridAghili

This problem is still unresolved after install Nova 3.21.0 and last version of nova-rtl-theme. #3 

![image](https://user-images.githubusercontent.com/22983388/106655205-4ddd5d80-65ae-11eb-899b-5068d5760a25.png)

Also there is some error in my console as you can see.

![image](https://user-images.githubusercontent.com/22983388/106655076-24243680-65ae-11eb-9362-4b40615a3cdb.png)

**Comment by FaridAghili** [comment]
Fixed in [v1.5.7](https://github.com/pishran/nova-rtl-theme/releases/tag/v1.5.7)

Thanks @SadeghPM

**Comment by ImanR7** [comment]
@SadeghPM Thank you so much
