### ISSUE TITLE
Arrow alignment in RTL mode

### ISSUE THREAD

**Issue by ImanR7** [pishran/nova-rtl-theme#15]
Hi,

@SadeghPM @FaridAghili 

Sorry, could you please fix arrow alignment in searchable fields?

![image](https://user-images.githubusercontent.com/22983388/107074358-ddc51680-67fd-11eb-808e-8286fa3e6c7a.png)

Thanks

**Comment by FaridAghili** [comment]
Fixed in [v1.5.8](https://github.com/pishran/nova-rtl-theme/releases/tag/v1.5.8) thanks to @SadeghPM.
