### ISSUE TITLE
fix rtl in  using Collapsible Resource Manager and nova-breadcrumbs

### ISSUE THREAD

**Issue by ssbahmed** [pishran/nova-rtl-theme#20]
Collapsible Resource Manager
https://github.com/dcasia/collapsible-resource-manager

nova-breadcrumbs

https://github.com/chris-ware/nova-breadcrumbs

<a href="https://ibb.co/nQvp5Xk"><img src="https://i.ibb.co/nQvp5Xk/Screenshot-from-2021-03-01-12-19-50.png" alt="Screenshot-from-2021-03-01-12-19-50" border="0"></a> <a href="https://ibb.co/3Y0818d"><img src="https://i.ibb.co/3Y0818d/Screenshot-from-2021-03-01-12-19-31.png" alt="Screenshot-from-2021-03-01-12-19-31" border="0"></a>

**Comment by FaridAghili** [comment]
Thanks

[v1.5.10](https://github.com/pishran/nova-rtl-theme/releases/tag/v1.5.10) released.
