### ISSUE TITLE
Vue Persian Date Picker Support

### ISSUE THREAD

**Issue by amidesfahani** [pishran/nova-rtl-theme#22]
hi
here is the problem with NovaPersianDatePicker Package

Packages:
[nova-persian-date](https://packagist.org/packages/amidesfahani/nova-persian-date)
[nova-persian-date-filter](https://packagist.org/packages/amidesfahani/nova-persian-date-filter)

![image](https://user-images.githubusercontent.com/61671721/120106183-5f580000-c171-11eb-9c77-1475a87928b5.png)

as you can see buttons are misplaced.

**Comment by amidesfahani** [comment]
`
.vpd-next, .vpd-prev {
    display: flex;
    align-items: center;
    justify-content: center;
}
`

**Comment by FaridAghili** [comment]
Hi,
Thanks for reporting, give me some time for testing.
