### ISSUE TITLE
nova trend metric width shrinks

### ISSUE THREAD

**Issue by aliwesome** [pishran/nova-rtl-theme#24]
did anyone face this problem below using this package?
 
![image](https://user-images.githubusercontent.com/21131502/147247414-dda43c83-2dd9-419e-84e8-b4a459f9195d.png)

**Comment by FaridAghili** [comment]
Yes, that's a bug which I'm aware of, couldn't fix it thu.
________________________________
From: Ali Sameni ***@***.***>
Sent: Thursday, December 23, 2021 5:01:00 PM
To: pishran/nova-rtl-theme ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pishran/nova-rtl-theme] nova trend metric width shrinks (Issue #24)


did anyone face this problem below using this package?

[image]<https://user-images.githubusercontent.com/21131502/147247414-dda43c83-2dd9-419e-84e8-b4a459f9195d.png>

**Comment by aliwesome** [comment]
@FaridAghili do you know any other discussion or issue I could join to find out if anyone found cause of this problem?

**Comment by aliwesome** [comment]
this is because of below code in `theme.css`
```
.ct-chart {
    right: unset !important;
    ...
}
```
we should know more about `ct-chart` and where it's being used before any changes.

**Comment by FaridAghili** [comment]
`.ct-chart` was used to align donut in partion metrics.

Fixed in [v1.5.13](https://github.com/pishran/nova-rtl-theme/releases/tag/v1.5.13)
