### ISSUE TITLE
Nova 4 support

### ISSUE THREAD

**Issue by NargesHajiani** [pishran/nova-rtl-theme#25]
- Laravel Version: 9.7.0
- Nova Version: 4.1.0
- PHP Version: 8.1

After upgrading Nova to 4.1.0 , nova-rtl-theme is no longer working.

**Comment by FaridAghili** [comment]
Yeap, that's true.
Currently I don't have access to Nova 4, so I can't test and develop for Nova 4.

**Comment by zayedadel** [comment]
Hello Mr. Farid I can give u a license to develop on so you can start making an rtl package 
email me at zayedadel95@gmail.com

**Comment by FaridAghili** [comment]
@zayedadel Thanks, sent you an email.

**Comment by FaridAghili** [comment]
Thanks to @taylorotwell, I got access to Nova 4 and soon we'll have Nova 4 RTL theme.

**Comment by zayedadel** [comment]
is there anything we can help with get the package ready any faster?

**Comment by emadbatwa** [comment]
is there any update @FaridAghili

**Comment by sinamiandashti** [comment]
@FaridAghili if u could tell us ur exact problem - we will help and create PR's

**Comment by FaridAghili** [comment]
Thank you all for your interest, I've already started working on this and it's almost finished.
Soon I'll release it.

**Comment by FaridAghili** [comment]
In searching for an alternative approach to add RTL support to Nova v4, I've suggested an automated way for adding RTL support to Nova's developers, please follow & support it here:
https://github.com/laravel/nova-issues/discussions/4306

**Comment by ObaydaAlesawi** [comment]
@FaridAghili Any updates for this?

**Comment by FaridAghili** [comment]
@Algeneralo Please check it here:
https://github.com/laravel/nova-issues/discussions/4306
