### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by mojtabaahn** [pishran/nova-rtl-theme#4]
سلام
هیچ راه ارتباطی با شما پیدا نکردم مجبور شدم issue باز کنم.
ایمیل خودتون (farid@pishranit.ir) و ایمیل آژانستونم Address not found میدن.
اگه یه ایمیل در دسترس قرار بدین خیلی خوب میشه ✌

**Comment by FaridAghili** [comment]
سلام
faridaghili@hotmail.com

راه‌های ارتباطی رو آپدیت می‌کنم
ممنون
