### ISSUE TITLE
Multi- language case

### ISSUE THREAD

**Issue by alwanof** [pishran/nova-rtl-theme#8]
in the case of multi-language, how to make the package work only if ar language selected?

**Comment by FaridAghili** [comment]
@alwanof Good point, check [v1.5.4](https://github.com/pishran/nova-rtl-theme/releases/tag/v1.5.4)

New config added to define RTL enabled locales, defaults to `fa` and `ar` for Persian and Arabic:

```php
'locales' => [
    'fa',
    'ar',
],
```

No CSS/JS will be injected in the case of other locales.
