### ISSUE TITLE
config error exception

### ISSUE THREAD

**Issue by ramisaaa** [pishran/nova-rtl-theme#9]
ErrorException 

  in_array() expects parameter 2 to be array, null given

  at vendor/pishran/nova-rtl-theme/src/ThemeServiceProvider.php:18

Hi .
after composer update today, I've received this error

**Comment by FaridAghili** [comment]
Hi, please update to the latest version and republish the config file:
```bash
php artisan vendor:publish --tag=nova-rtl-theme --force
```
